import type { ProblemContent } from "dsa-bot-content-schema";

function esc(value: string): string {
  return value.replace(/'/g, "''");
}

function canonicalApproach(doc: ProblemContent) {
  const approach = doc.approaches.find((a) => a.id === doc.canonicalApproachId);
  if (!approach) {
    throw new Error(`Missing canonical approach ${doc.canonicalApproachId}`);
  }
  return approach;
}

export function emitProblemRow(doc: ProblemContent, id: number): string {
  const canonical = canonicalApproach(doc);
  const solutions = {
    python: canonical.implementations.python,
    go: canonical.implementations.go,
    rust: canonical.implementations.rust,
  };
  const contentJson = esc(JSON.stringify(doc));

  return `INSERT OR REPLACE INTO problems (
  id, slug, day_number, title, description, difficulty, pattern, topic,
  examples_json, key_insight, applications_json, variations_json, why_it_matters,
  canonical_approach, canonical_solutions_json, hints_json, complexity,
  test_cases_json, license, source_url, content_json
) VALUES (
  ${id}, '${esc(doc.slug)}', ${doc.meta.day}, '${esc(doc.meta.title)}', '${esc(doc.statement.description)}',
  '${doc.meta.difficulty}', '${esc(doc.meta.pattern)}', '${esc(doc.meta.topic)}',
  '${esc(JSON.stringify(doc.statement.examples))}',
  '${esc(doc.learning.keyInsight)}',
  '${esc(JSON.stringify(doc.applications))}',
  '${esc(JSON.stringify(doc.variations))}',
  '${esc(doc.learning.whyItMatters)}',
  '${esc(canonical.summary)}',
  '${esc(JSON.stringify(solutions))}',
  '${esc(JSON.stringify(doc.hints))}',
  '${esc(canonical.complexity.time.notation)}',
  '${esc(JSON.stringify(doc.testCases))}',
  '${esc(doc.license)}',
  '${esc(doc.source.url)}',
  '${contentJson}'
);`;
}

export function emitSeedSql(docs: ProblemContent[]): string {
  const sorted = [...docs].sort((a, b) => a.meta.day - b.meta.day);
  const header = ["-- Generated by content pipeline"];
  const rows = sorted.map((doc, index) => emitProblemRow(doc, index + 1));
  return [...header, ...rows].join("\n");
}
