import type { ProblemRecord } from "./types";

function esc(value: string): string {
  return value.replace(/'/g, "''");
}

export function emitSeedSql(records: ProblemRecord[]): string {
  const header = [
    "-- Generated by ingest pipeline",
    "BEGIN TRANSACTION;",
  ];

  const rows = records.map((r) => {
    return `INSERT OR REPLACE INTO problems (
  id, slug, day_number, title, description, difficulty, pattern, topic,
  examples_json, key_insight, applications_json, variations_json, why_it_matters,
  canonical_approach, canonical_solutions_json, hints_json, complexity,
  test_cases_json, license, source_url
) VALUES (
  ${r.id}, '${esc(r.slug)}', ${r.day_number}, '${esc(r.title)}', '${esc(r.description)}',
  '${r.difficulty}', '${esc(r.pattern)}', '${esc(r.topic)}',
  '${esc(r.examples_json)}', '${esc(r.key_insight)}', '${esc(r.applications_json)}',
  '${esc(r.variations_json)}', '${esc(r.why_it_matters)}', '${esc(r.canonical_approach)}',
  '${esc(r.canonical_solutions_json)}', '${esc(r.hints_json)}', '${esc(r.complexity)}',
  '${esc(r.test_cases_json)}', '${esc(r.license)}', '${esc(r.source_url)}'
);`;
  });

  return [...header, ...rows, "COMMIT;"].join("\n");
}
