name = "dsa-bot-worker"
main = "src/index.ts"
compatibility_date = "2026-04-21"

[[d1_databases]]
binding = "DB"
database_name = "dsa-bot"
database_id = "0e319c27-fb22-4497-9bc1-818c5f1a4fe6"

[[kv_namespaces]]
binding = "CACHE"
id = "7e4f2ad9684843f39324d9b21698911c"

[[queues.producers]]
queue = "broadcast"
binding = "BROADCAST_QUEUE"

[[queues.consumers]]
queue = "broadcast"
max_batch_size = 30
max_batch_timeout = 10

[triggers]
crons = ["0 13 * * *", "30 13 * * *"]
